.PHONY: all

all:
	#gcc -o train ../src/*.c ./train.c -lm -lpthread -O3 -mavx2 -g
	#gcc -o memcheck ../src/*.c ./memcheck.c -lm -lpthread -O3 -mavx2 -g
	#gcc -o neat ../src/*.c ./neat.c -lm -lpthread -O3 -mavx2 -g
	#gcc -o dqn ../src/*.c ./dqn.c -lm -lpthread -O3 -mavx2 -g
	gcc -o rainbow ../src/*.c ./rainbow.c -lm -lpthread -O3 -mavx2 -g
	#gcc -o wrong_model_memchecker ../src/*.c wrong_model_memchecker.c -lm -lpthread -O3 -mavx2 -g
